### ISSUE TITLE
Does not work - only opens empty regular tab

### ISSUE THREAD

**Issue by krokofant** [ollide/Xposed-IncognitoTab#1]
IncognitoTab: 1.1 (2015-03-26)
Xposed version: 3.0 alpha2
Chrome stable: 42.0.2311.111
OS: Cyanogen OS 12.0 Based on Android 5.0.2

Xposed log:

```
05-07 21:28:49.286 E/Xposed  (18193): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.google.android.apps.chrome.utilities.FeatureUtilitiesInternal
05-07 21:28:49.286 E/Xposed  (18193):   at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
05-07 21:28:49.286 E/Xposed  (18193):   at org.ollide.xposed.incognitotab.ChromeUtils.isDocumentMode(ChromeUtils.java:16)
05-07 21:28:49.286 E/Xposed  (18193):   at org.ollide.xposed.incognitotab.MethodHooks$1.afterHookedMethod(MethodHooks.java:45)
05-07 21:28:49.286 E/Xposed  (18193):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:670)
05-07 21:28:49.286 E/Xposed  (18193):   at com.google.android.apps.chrome.document.ChromeLauncherActivity.onCreate(Unknown Source)
05-07 21:28:49.286 E/Xposed  (18193):   at android.app.Activity.performCreate(Activity.java:5933)
05-07 21:28:49.286 E/Xposed  (18193):   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
05-07 21:28:49.286 E/Xposed  (18193):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
05-07 21:28:49.286 E/Xposed  (18193):   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
05-07 21:28:49.286 E/Xposed  (18193):   at android.app.ActivityThread.access$900(ActivityThread.java:147)
05-07 21:28:49.286 E/Xposed  (18193):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
05-07 21:28:49.286 E/Xposed  (18193):   at android.os.Handler.dispatchMessage(Handler.java:102)
05-07 21:28:49.286 E/Xposed  (18193):   at android.os.Looper.loop(Looper.java:135)
05-07 21:28:49.286 E/Xposed  (18193):   at android.app.ActivityThread.main(ActivityThread.java:5254)
05-07 21:28:49.286 E/Xposed  (18193):   at java.lang.reflect.Method.invoke(Native Method)
05-07 21:28:49.286 E/Xposed  (18193):   at java.lang.reflect.Method.invoke(Method.java:372)
05-07 21:28:49.286 E/Xposed  (18193):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
05-07 21:28:49.286 E/Xposed  (18193):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
05-07 21:28:49.286 E/Xposed  (18193):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
05-07 21:28:49.286 E/Xposed  (18193): Caused by: java.lang.ClassNotFoundException: com.google.android.apps.chrome.utilities.FeatureUtilitiesInternal
05-07 21:28:49.286 E/Xposed  (18193):   at java.lang.Class.classForName(Native Method)
05-07 21:28:49.286 E/Xposed  (18193):   at java.lang.Class.forName(Class.java:308)
05-07 21:28:49.286 E/Xposed  (18193):   at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
05-07 21:28:49.286 E/Xposed  (18193):   at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
05-07 21:28:49.286 E/Xposed  (18193):   ... 18 more
05-07 21:28:49.286 E/Xposed  (18193): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.chrome.utilities.FeatureUtilitiesInternal" on path: DexPathList[[zip file "/data/app/com.android.chrome-1/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-1/lib/arm, /vendor/lib, /system/lib]]
05-07 21:28:49.286 E/Xposed  (18193):   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-07 21:28:49.286 E/Xposed  (18193):   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-07 21:28:49.286 E/Xposed  (18193):   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-07 21:28:49.286 E/Xposed  (18193):   ... 22 more
05-07 21:28:49.286 E/Xposed  (18193):   Suppressed: java.lang.ClassNotFoundException: com.google.android.apps.chrome.utilities.FeatureUtilitiesInternal
05-07 21:28:49.286 E/Xposed  (18193):       at java.lang.Class.classForName(Native Method)
05-07 21:28:49.286 E/Xposed  (18193):       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-07 21:28:49.286 E/Xposed  (18193):       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-07 21:28:49.286 E/Xposed  (18193):       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-07 21:28:49.286 E/Xposed  (18193):       ... 23 more
05-07 21:28:49.286 E/Xposed  (18193):   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

```

**Comment by EnejV** [comment]
I can confirm this, although I installed 1.0 version (beta) and it works. So there must be something wrong with the 1.1 version...

**Comment by krokofant** [comment]
Oh, thanks :+1:

**Comment by go-vegan** [comment]
I can confirm this too, with both v1 and v1.1.
Xposed version: 3.0 alpha2
Chrome stable: 43.0.2357.93
ROM: CloudyG3 2.3 (Android 5.0.0)

Any fix estimation?

**Comment by oxwivi** [comment]
Two years old, but I'mma just add it still doesn't work. If anyone for any alternatives, do tell.

**Comment by krokofant** [comment]
@oxwivi Check out Firefox Focus, it's a better non-xposed replacement.

https://play.google.com/store/apps/details?id=org.mozilla.focus

**Comment by oxwivi** [comment]
@krokofant, I've used and given up on it before once again seeking solutions like this. It's Webkit-based for some reason despite being from Mozilla and its tab mechanism is plain horrible.
